/*
Deployment script for CIEDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

:setvar DatabaseName "CIEDB"
:setvar DefaultFilePrefix "CIEDB"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO

PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)] COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO

USE [$(DatabaseName)];


GO

PRINT N'Creating [dbo].[User]...';


GO
CREATE TABLE [dbo].[User] (
    [Id]       INT              IDENTITY (1, 1) NOT NULL,
    [Name]     VARCHAR (50)     NOT NULL,
    [UserName] VARCHAR (20)     NOT NULL,
    [Password] VARCHAR (50)     NOT NULL,
    [GUID]     UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[User].[IX_User_Column]...';


GO
CREATE NONCLUSTERED INDEX [IX_User_Column]
    ON [dbo].[User]([UserName] ASC);


GO
PRINT N'Creating [dbo].[Item]...';


GO
CREATE TABLE [dbo].[Item] (
    [Id]      INT          IDENTITY (1, 1) NOT NULL,
    [UserId]  INT          NOT NULL,
    [Message] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Item].[IX_Item_Column]...';


GO
CREATE NONCLUSTERED INDEX [IX_Item_Column]
    ON [dbo].[Item]([UserId] ASC);


GO
PRINT N'Creating [dbo].[FK_Item_ToTable]...';


GO
ALTER TABLE [dbo].[Item]
    ADD CONSTRAINT [FK_Item_ToTable] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id]);


GO
PRINT N'Creating [dbo].[UserGet]...';


GO
CREATE PROCEDURE [dbo].[UserGet]
	@id int = 0
AS

	SELECT * FROM [User]
	WHERE Id = @id;
GO
PRINT N'Creating [dbo].[UserGetByUserName]...';


GO
CREATE PROCEDURE [dbo].[UserGetByUserName]
	@UserName varchar(20)

AS
	SELECT * FROM [User]
	WHERE UserName = @UserName;
GO
PRINT N'Creating [dbo].[UserAdd]...';


GO
CREATE PROCEDURE [dbo].[UserAdd]
	@Name varchar(20),
	@UserName varchar(20),
	@Password varchar(50),
	@GUID uniqueidentifier
AS
	
INSERT INTO [User] 
	(Name, UserName, [Password], [GUID])
VALUES
	(@Name, @UserName, @Password, @GUID);
GO
PRINT N'Creating [dbo].[ItemGet]...';


GO
CREATE PROCEDURE [dbo].[ItemGet]
	@id int = 0
AS
	SELECT * FROM Item
	WHERE Id = @id;
GO
PRINT N'Creating [dbo].[ItemAdd]...';


GO
CREATE PROCEDURE [dbo].[ItemAdd]
	@userId int=0,
	@message varchar(50)
AS
	INSERT INTO Item
		(UserId, [Message])
	VALUES
		(@userId, @message);
GO
PRINT N'Creating [dbo].[ItemList]...';


GO
CREATE PROCEDURE [dbo].[ItemList]
AS
BEGIN
	SELECT tb1.Id, tb1.UserId, tb1.[Message], tb2.Name 
	FROM Item tb1 INNER JOIN [User] tb2
	ON tb1.UserId = tb2.Id;
END
GO
PRINT N'Creating [dbo].[ItemDelete]...';


GO
CREATE PROCEDURE [dbo].[ItemDelete]
	@id int = 0
AS
	DELETE FROM Item
	WHERE Id = @id;
GO
PRINT N'Creating [dbo].[ItemUpdate]...';


GO
CREATE PROCEDURE [dbo].[ItemUpdate]
	@id int = 0,
	@userID int = 0,
	@message varchar(50)
AS
	UPDATE Item
	SET UserId = @userID, [Message] = @message
	WHERE Id = @id;
GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET MULTI_USER 
    WITH ROLLBACK IMMEDIATE;


GO
PRINT N'Update complete.';


GO
